version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - "8001:8001" # Si no pongo el primer puerto, hago que no se exponga y no podamos acceder directamente

  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - "8002:8002"

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - "8003:8003"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "8004:8004"